### PR TITLE
Added files flag

### PR DESCRIPTION
**Pull request by willemneal**
--file or -f now filters out tests file names via cli

### CODE REVIEW

**Comment by jtenner** [comment]
FWIW the lib conflicts can be completely ignored, and the package-lock can be deleted/regenerated later.

**Comment by willemneal** [comment]
@jtenner Not sure why the coverage dropped, but otherwise how does it look?

**Comment by jtenner** [comment]
Idk why coverage dropped either. 

Among other things It looks like the types in the package.json need to point to lib/as-pect.d.ts

**Comment by jtenner** [comment]
I promise to take a look at this tomorrow. I just happen to be very busy today.

**Comment by jtenner** [comment]
The file affected looks like src/test/TestResult.ts:102

This is for variance calculations. Is there any way to force a pull request that doesn't pass onto master?

**Comment by jtenner** [comment]
I will handle this pull request tomorrow for sure. Sorry I couldn't get around to it. Mother's day and all!

**Pull request merged**
