### PR TITLE
refactor: directly use javascript interop functions

### PR DESCRIPTION
**Pull request by 9oelM**

### CODE REVIEW

**Comment by jtenner** [comment]
Okay this pull request is awesome.

A few things:

1. We should only need 4 linked functions for test creation
  - reportTestNode -> Should create a child test on the current node
  - reportGroupNode -> Should create a child group on the current node
  - reportTodo -> Should create a todo
  - reportNegatedTestNode -> Should create a negated test
2. Each of those linked functions should be accessed differently by the assembly package

```ts
// both of these functions can point to the same linked function
@external("__aspect", "reportNegatedTest")
declare function itThrows(desc: string, callback: () => void): void;
@external("__aspect", "reportNegatedTest")
declare function throws(desc: string, callback: () => void): void;

// utilize todo functions the same way
@external("__aspect", "reportTodo")
declare function todo(desc: string): void;

// the callback can simply be ignored in the host
@external("__aspect", "reportTodo")
declare function xit(desc: string, callback: () => void): void;
// the callback can simply be ignored in the host
@external("__aspect", "reportTodo")
declare function xtest(desc: string, callback: () => void): void;
```

**Comment by 9oelM** [comment]
@jtenner thank you. I will make changes accordingly :)

**Comment by jtenner** [comment]
Hey. What's the status on this? I'd love to pull this.

**Comment by 9oelM** [comment]
Not sure why this piece of log differs from the previous snapshot:

```
  -      [Log]: Float64Array [ 0.0, 1.0, 2.0... +17 items ]
    +      [Log]: Float64Array [ 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0... +10 items ]

```

**Comment by jtenner** [comment]
Also, please pull master.

**Comment by jtenner** [comment]
Thank you!

**Pull request merged**
