### PR TITLE
Add lerna badge

### PR DESCRIPTION
**Pull request by willemneal**

### CODE REVIEW

**Comment by jtenner** [comment]
Is it acceptable to add a Paypal donate link? Or a few btc addresses? :)

**Comment by jtenner** [comment]
We should also add the lerna badge to all the readmes in the packages, if that's okay.

**Comment by willemneal** [comment]
@jtenner Do you want to make a BTC or ETH wallet for the org?

Also what is your paypal account?

**Comment by willemneal** [comment]
Also you should send the lerna people a message and get put on their list of projects that use lerna 👍

**Comment by jtenner** [comment]
paypal.me/JoshuaTenner

**Comment by jtenner** [comment]
btc: 3JBsChy5UkuoEJGjhXpdBMNXypzwUdR82n

**Comment by jtenner** [comment]
We can worry about donations later. Thank you for this pull request.

**Pull request merged**
