### PR TITLE
fix: experimental-wasm-bigint does not need for node 16 and above

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by jtenner** [comment]
Yeah it looks like the flags changes might cause the snapshots to be different. My guess is removing test support lts the right call here.

We can support the old version <=15, but it might be better not to run tests for it.

**Comment by MaxGraey** [comment]
Ok, you're free to change / improve this PR as you want.

**Comment by jtenner** [comment]
I love the change. Let me do a bit of experimentation to see what it means. Thank you very much for starting it.

**Comment by MaxGraey** [comment]
Unfortunately I can;t update snapshots:
```
lerna ERR! npm run test:latest:update-snapshots exited 1 in '@as-pect/core'
lerna ERR! npm run test:latest:update-snapshots stdout:

> @as-pect/core@6.0.0 test:latest:update-snapshots
> node --experimental-wasi-unstable-preview1 --experimental-vm-modules ./node_modules/jest/bin/jest.js -u
```
and a lot of errors:
```
__tests__/VerboseReporter.snapshot.spec.ts:5:26 - error TS2307: Cannot find module '@as-pect/snapshots'.

    5 import { Snapshot } from "@as-pect/snapshots";
                               ~~~~~~~~~~~~~~~~~~~~
```
```
FAIL __tests__/TestContext.spec.ts
  ● Test suite failed to run

    src/reporter/SummaryReporter.ts:5:40 - error TS2307: Cannot find module '@as-pect/snapshots'.

    5 import { SnapshotDiffResultType } from "@as-pect/snapshots";
                                             ~~~~~~~~~~~~~~~~~~~~
```
and etc

**Comment by jtenner** [comment]
Closed in favor of #341 credit to @MaxGraey for making the necessary bin file change.

**Pull request closed without merging**
