### PR TITLE
Fix dataLength and loader API

### LINKED ISSUE #157: Data Length property needs to be refactored.
```
ERROR TS2339: Property 'dataLength' does not exist on type '~lib/arraybuffer/ArrayBufferView'.

   if (actual.dataLength != expected.dataLength) {
              ~~~~~~~~~~
 in node_modules/@as-pect/assembly/assembly/internal/comparison/arrayComparison.ts(49,13)

ERROR TS2339: Property 'dataLength' does not exist on type '~lib/arraybuffer/ArrayBufferView'.

   if (actual.dataLength != expected.dataLength) {
                                     ~~~~~~~~~~
 in node_modules/@as-pect/assembly/assembly/internal/comparison/arrayComparison.ts(49,36)
```

### LINKED ISSUE #159: Fix Loader API instantiateBuffer -> ""Sync

### PR DESCRIPTION
**Pull request by willemneal**
fixes #159 
fixes #157

### CODE REVIEW

**Comment by willemneal** [comment]
```
TypeError: Unable to require `.d.ts` file.
    This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension available alongside `IPerformanceConfiguration.ts`.
      at getOutput (../../node_modules/ts-jest/dist/compiler.js:163:23)
      at Object.compile (../../node_modules/ts-jest/dist/compiler.js:206:25)
      at TsJestTransformer.process (../../node_modules/ts-jest/dist/ts-jest-transformer.js:101:41)
      at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:453:35)
      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:523:40)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
```

Any ideas @jtenner ?

**Comment by jtenner** [comment]
I'll take a look at this later. Mind if I try some commits to this branch?

**Comment by willemneal** [comment]
Go for it

**Comment by jtenner** [comment]
Does this ship with @MaxGraey's pull request?

**Comment by jtenner** [comment]
@MaxGraey this is going to stop working until assemblyscript master updates dist files because of `isNaN<T>()`.

Sorry to block your workflow.

**Comment by jtenner** [comment]
@willemneal Please review.

**Comment by jtenner** [comment]
This should be the last pull request and I'll ensure that 2.6.0 ships to npm.

**Pull request merged**
